demo.greeting=Hello with conditional Redis
spring.go-redis.enabled=true
spring.go-redis.addr=127.0.0.1:6379
spring.go-redis.instances.cache.addr=127.0.0.1:6379
spring.go-redis.instances.queue.addr=127.0.0.1:6380
