demo.greeting=Hello under test
demo.audience=testable controller
spring.go-redis.addr=127.0.0.1:6379

logging.logger.root.type=ConsoleLogger
logging.logger.root.level=INFO
logging.logger.root.layout.type=JSONLayout
logging.logger.root.layout.fileLineMaxLength=80
